### ISSUE TITLE
NURBS test failing

### ISSUE THREAD

**Issue by danielepanozzo** [qnzhou/nanospline#49]
I am getting this failure on:
1. gcc version 11.3.0 (Ubuntu 11.3.0-1ubuntu1~22.04):
2. gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)

-------------------------------------------------------------------------------
Inverse evaluation debug 5
  Query 2
-------------------------------------------------------------------------------
/home/daniele/git/nanospline/tests/test_NURBSPatch.cpp:1763
...............................................................................

/home/daniele/git/nanospline/tests/test_NURBSPatch.cpp:1772: FAILED:
  REQUIRE( (q - p).norm() == Approx(0).margin(1e-6) )
with expansion:
  0.4131266255 == Approx( 0.0 )

**Comment by qnzhou** [comment]
Yes, this is a known failure example.  The unit test is using the most generic form of inverse evaluation:
```c++
patch.inverse_evaluate(query_point, min_u, max_u, min_v, max_v);
```

While it is convenient, it is doing a (recursive) brute force sampling of the patch and use the best sample point as the starting point to start a Newton iteration.  Therefore, there is no guarantees that the inverse evaluation will converge.
A better way is to provide a good enough initial guess and kick start Newton iteration directly:
```c++
patch.inverse_evaluate(query_point, 
    init_u, init_v,              // Initial guess of the solution.
    min_u, max_u, min_v, max_v,  // The valid domain.
    num_iterations);             // Other parameters
```

**Comment by mmorse1217** [comment]
Just a quick follow up (sorry for the delay): I think `patch.inverse_evaluate(query_point, min_u, max_u, min_v, max_v)` is doing something more fancy than just sampling now: it seems like it is recursively checking the nearest weighted control points via subdivision for an initial guess and passing this to Newton. I'm not sure about this test case in particular, but  non-manifold NURBS isn't robustly handled here and could be the problem.

**Comment by qnzhou** [comment]
@mmorse1217 Thanks!  Do you have any suggestions about a more robust way of computing the closest point?  I recall you shared some paper with me before, but I cannot find it now...

**Comment by mmorse1217** [comment]
I think [this is the paper](https://www.sciencedirect.com/science/article/abs/pii/S0167839603000219) we had discussed at the time, but I will double check to be sure. I'm not sure if this is state of the art since the paper is somewhat old, but they have some non-manifold curve examples. 

Broadly, the steps are similar to the implemented version:
1. Split the NURBS patch into subpatches (actually Bezier patches)
2. Check if subpatches' control point net are "valid" (i.e. simple and convex) or not; if a control point net is invalid, repeat recursively until all are valid.
3. For each valid control point net, check some quick geometric relationship between the query point and the control net: ignore all patches that have a closest point to the query point on the patch boundary (with some kind of acceleration).
4. For all remaining patches, project query onto the patch directly and choose the closest projection.
5. This projection is used as an initial guess for Newton.

Patch splitting is already implemented in nanospline, so I think the only bits that would need to be implemented are the control point net checks and the patch projections. 

I have a vague memory of a discussion about this potentially needing some kind of AABB-esque data structure to be practical, so we decided against it at the time. There is likely a way around this requirement, though, and there may be a more recent paper with a smarter solution.
